
"2025/26":

  cgt_allowance: 0

  basic_income_limit: 38123

  basic_cgt_rate: 0.10

  higher_cgt_rate: 0.20

  taxable_income: 59000

"2026/27":

  cgt_allowance: 0

  basic_income_limit: 38123

  basic_cgt_rate: 0.10

  higher_cgt_rate: 0.20

  taxable_income: 59000