name: Trading System CI

on:

  pull_request:

    branches:
      - main
      - branches

jobs:

  test:

    runs-on: ubuntu-latest

    env:
      APP_ENV: test

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: pytest