tickers:
- A
- AAOI
- AAPL
- ADBE
- AEHR
- AI
- ALAB
- AMBA
- AMD
- AMZN
- ANET
- APP
- ARKK
- ARM
- ASML
- AVGO
- B
- BBAI
- BMW.DE
- C
- CDNS
- CEG
- CRDO
- CRWD
- CRWV
- CSCO
- D
- DDOG
- DELL
- DIS
- DT
- E
- ENVX
- ETN
- F
- FIVN
- FTNT
- G
- GOOG
- H
- HOOD
- I
- IBM
- INOD
- INTC
- IONQ
- IWM
- K
- KLAC
- L
- LPTH
- LWLG
- M
- MCD
- MDB
- META
- MRVL
- MSFT
- MU
- N
- NET
- NKE
- NOW
- NVDA
- O
- ORCL
- P
- PANW
- PATH
- PG
- PLAB
- POET
- Q
- QLYS
- QQQ
- R
- ROK
- RXRX
- S
- SAP
- SCHW
- SGE.L
- SKYT
- SMCI
- SMH
- SMR
- SNDK
- SNOW
- SNPS
- SOUN
- SOXX
- SPY
- SWKS
- SYM
- T
- TEM
- TSLA
- TSM
- TWLO
- U
- V
- VRT
- W
- WDAY
- X
- Y
- Z
- ZS
