name: Trading_System_CI_Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: system pipeline test
        run: pytest tests2/test2_system_pipeline.py -s -v --tb=long --capture=no
      - name: market pipeline test
        run: pytest tests2/test2_market_pipeline.py -s -v --tb=long --capture=no
      - name: sell pipeline test
        run: pytest tests2/test2_sell_pipeline.py -s -v --tb=long --capture=no
