name: Trading System CI

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r ../requirements.txt

      - run: pytest tests2/test2_market_analysis_pipeline_main.py -v
      - run: pytest tests2/test2_system_pipeline_main.py -v
