name: Trading System CI

on:

  pull_request:

    branches:
      - main

env:

  APP_ENV: prod

jobs:
  price-cache-pipeline:

    name: Market Analysis Pipeline

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: >
          PYTHONPATH=${{ github.workspace }}
          pytest tests2/test2_price_cache_pipeline.py
          -s
          -v

  market-analysis-pipeline:

    name: Market Analysis Pipeline

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: >
          PYTHONPATH=${{ github.workspace }}
          pytest tests2/test2_market_analysis_pipeline.py
          -s
          -v

  system-pipeline:

    name: System Pipeline

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: >
          PYTHONPATH=${{ github.workspace }}
          pytest tests2/test2_system_pipeline.py
          -s
          -v

  sell-pipeline:

    name: Sell Pipeline

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: >
          PYTHONPATH=${{ github.workspace }}
          pytest tests2/test2_sell_pipeline.py
          -s
          -v
          --tb=long
          --capture=no
        
  capital-pipeline:

    name: Capital Pipeline

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: >
          PYTHONPATH=${{ github.workspace }}
          pytest tests2/test2_capital_pipeline.py
          -s
          -v
  position-sizing-pipeline:

    name: Position Sizing Pipeline

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: >
          PYTHONPATH=${{ github.workspace }}
          pytest tests2/test2_position_sizing_pipeline.py
          -s
          -v

  success:

    name: All Tests Complete

    runs-on: ubuntu-latest

    needs:

      - price-cache-pipeline
      - capital-pipeline
      - market-analysis-pipeline
      - sell-pipeline
      - system-pipeline
      - position-sizing-pipeline

    steps:

      - run: echo "All tests passed successfully!..."