name: Trading System CI

on:

  pull_request:

    branches:
      - main

env:

  APP_ENV: prod

jobs:
  run-project-pytests:
    permissions:
          contents: read
          pull-requests: write
          
    name: Run Project Pytests

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: >
          PYTHONPATH=${{ github.workspace }}
          pytest
          -s
          -v

  success:

    name: All Tests Complete

    runs-on: ubuntu-latest

    steps:

      - run: echo "All tests passed successfully!..."