name: Trading System CI

on:

  pull_request:

    branches:
      - test
      - main

  push:

    branches:
      - test
      - main

jobs:

  pytests:

    permissions:
          contents: read
          pull-requests: write
          
    name: Run Project Pytests

    runs-on: ubuntu-latest

    env: 
      
      APP_ENV: test

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: >
          PYTHONPATH=${{ github.workspace }}
          pytest
          -s
          -v

      - run: echo "All tests have executed successfully!..."